<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.yingzi</groupId>
    <artifactId>springai-alibaba-quickstart</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.9</version>
    </parent>

    <modules>
        <module>Chat-Model</module>
        <module>Advisor</module>
        <module>Advisor-Memory</module>
        <module>Tool-Calling</module>
        <module>Mcp</module>
        <module>Mcp/mcp-client-stdio</module>
        <module>Mcp/mcp-server-stdio</module>
        <module>Mcp/mcp-server-webflux</module>
        <module>Mcp/mcp-client-webflux</module>
        <module>Alibaba-Api-Example</module>
        <module>Structured-Output</module>
        <module>Rag</module>
        <module>Vector-Databases</module>
        <module>Vector-Databases/vector-elasticsearch-exmaple</module>
        <module>Vector-Databases/vector-redis-example</module>
        <module>Vector-Databases/vector-simple-example</module>
        <module>Graph</module>
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <spring-boot.version>3.3.9</spring-boot.version>
        <spring-ai.version>1.0.0-M7</spring-ai.version>
        <ai-alibaba.version>1.0.0-M6.1</ai-alibaba.version>
        <openai.version>1.0.0-M6</openai.version>
        <dashscope-sdk-java.version>2.18.5</dashscope-sdk-java.version>
        <mcp.version>0.8.1</mcp.version>
    </properties>

    <dependencyManagement>
        <dependencies>
<!--          spring AI 源码部分-->
            <dependency>
                <groupId>org.springframework.ai</groupId>
                <artifactId>spring-ai-bom</artifactId>
                <version>${spring-ai.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

<!--            阿里-->
            <dependency>
                <groupId>com.alibaba.cloud.ai</groupId>
                <artifactId>spring-ai-alibaba-starter</artifactId>
                <version>${ai-alibaba.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>dashscope-sdk-java</artifactId>
                <version>${dashscope-sdk-java.version}</version>
            </dependency>
<!--            OpenAI-->
            <dependency>
                <groupId>org.springframework.ai</groupId>
                <artifactId>spring-ai-openai-spring-boot-starter</artifactId>
                <version>${openai.version}</version>
            </dependency>

<!--            mcp版本选择-->
            <dependency>
                <groupId>io.modelcontextprotocol.sdk</groupId>
                <artifactId>mcp</artifactId>
                <version>${mcp.version}</version>
            </dependency>

<!--            其他SpringBoot常见框架-->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-web</artifactId>
                <version>${spring-boot.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>


    <repositories>

        <!-- Spring AI 官方仓库，唯一能找到这些依赖的地方 -->
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>

        <repository>
            <name>Central Portal Snapshots</name>
            <id>central-portal-snapshots</id>
            <url>https://central.sonatype.com/repository/maven-snapshots/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/libs-milestone-local</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <releases>
                <enabled>true</enabled>
            </releases>
        </repository>
        <repository>
            <id>spring-snapshots</id>
            <name>Spring Snapshots</name>
            <url>https://repo.spring.io/snapshot</url>
            <releases>
                <enabled>true</enabled>
            </releases>
        </repository>
    </repositories>

</project>