server:
  port: 8080

spring:
  application:
    name: Chat-Model

  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}

      chat:
        options:
          model: qwen-turbo
          spring:
        client:
          connect-timeout: 10s
          read-timeout: 60s
          write-timeout: 10s
